{% set name = "napari-segment-blobs-and-things-with-membranes" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-segment-blobs-and-things-with-membranes-{{ version }}.tar.gz
  sha256: f1fc818c61212fed9c01d72d364500a93216ebec0ff4475b528ecf0f4880b719

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - napari
    - napari-plugin-engine >=0.1.4
    - napari-time-slicer
    - napari-tools-menu >=0.1.17
    - numpy
    - python >=3.7
    - scikit-image
    - scipy
    - napari-assistant
    - stackview >=0.3.2

test:
  imports:
    - napari_segment_blobs_and_things_with_membranes
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes
  summary: A plugin based on scikit-image for segmenting nuclei and cells based on fluorescent microscopy images with high intensity in nuclei and/or membranes
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
