{% set name = "napari-segment-blobs-and-things-with-membranes" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8791bc28c3a759043cfb505ca4d412bfb9482cdcc57080ced11f1e8672eb6a26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - napari
    - napari-assistant  # Declared in requirements but not imported
    - napari-plugin-engine >=0.1.4
    - napari-time-slicer >=0.4.8  # Declared in requirements but not imported
    - napari-tools-menu >=0.1.17
    - numpy
    - python >={{ python_min }},<3.11
    - scikit-image
    - scipy
    - stackview >=0.3.2

test:
  imports:
    - napari_segment_blobs_and_things_with_membranes
  commands:
    - pip list
    # - pip check  # napari-assistant 0.4.6 requires jupyter and jupytext
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-segment-blobs-and-things-with-membranes
  summary: |
    A plugin based on scikit-image for segmenting nuclei and cells based on fluorescent
    microscopy images with high intensity in nuclei and/or membranes.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
